### ISSUE TITLE
The AND operator in query treated as keyword

### ISSUE THREAD

**Issue by susheelks** [renekrie/querqy#22]
Hello Rene,

I was looking further into querqy for my use case and realized that when i execute a query like below

query
==
http://localhost:8983/solr/test/select?indent=on&q=text:Rich AND Active&defType=querqy&wt=json&debugQuery=true

debuq
==
"querystring": "text:Rich AND Active",
"parsedquery": "text:text:rich text:and text:active",

the keyword AND is treated as "and" and thus returning unexpected results while with edismax / default query parser it returns expected result by 

debuqQuery
==
querystring": "text:Rich AND Active",
"parsedquery": "(+(+text:rich +DisjunctionMaxQuery((text:active))))/no_coord",

OR (with dismax)
"querystring": "text:Rich AND Active",
"parsedquery": "+text:rich +text:active",

Please suggest.

**Comment by renekrie** [comment]
Querqy's WhiteSpaceQuerqyParser currently does not support these Boolean operators, only + and - prefixes would be allowed. On the other hand, Querqy's internal query object model would support boolean semantics => you could write a Querqy query parser that creates the internal query treating AND/OR as operators. You might also consider using the mm parameter.
