### ISSUE TITLE
WordBreakCompoundRewriter should support case-insensitive dictionaries

### ISSUE THREAD

**Issue by mkr** [renekrie/querqy#39]
Currently, the WordBreakCompoundRewriter validates candidates for compounds and term constituents against a dictionary field. There is no pre-processing/analysis before validation so a upper-case search term will never validate against a lowercased dictionary field, i.e. "Hunde Futter" will never be compounded if there is only "hundefutter" indexed in the dictionary field.

Two possible fixes:
* Get the field's query analyzer from the Solr schema and perform analysis before term validation.
* Provide an option to just lowercase the term before validation.

**Comment by renekrie** [comment]
Thank you! I think we should use the second approach (just lowercase) as this happens in querqy-lucene, where we don't have a guarantee that there is a schema.

**Comment by renekrie** [comment]
This has been implemented.
