### ISSUE TITLE
Common Rules ordering/limiting should support 'levels'

### ISSUE THREAD

**Issue by renekrie** [renekrie/querqy#53]
In the Common Rules rewriter, rules can be sorted by a property and then the top n rules can be selected using the `limit` parameter. Though this is already useful when we want to promote a specific rule over a generic rule (such as 'notebook bag' vs 'notebook' - prio 10 vs prio 1 and sort=prio desc & limit=1), there might be a varying number of high priority rules that we want to apply before filtering out lower priority rules.

The suggested solution uses a new parameter 'limit.level=true|false'. If it is 'true' rules will be sorted by the sort parameter as before (sort=prop desc) but if two rules have the same value for the sort criterion, they will only count as one unit towards the limit.

Let there be a third rule for 'bag', also having prio = 10, then `sort=prio desc&limit=1&limit.level=true`, will allow rules for 'notebook bag' and 'bag' - both at the same prio 'level' (10) - to be included, but 'notebook' (prio=1, next level) to be excluded.

**Comment by MighTguY** [comment]
Hi @renekrie,
I have a few thoughts on the same: 
1. In the case of a tie, we can also pick the one which has been latest updated, this will also honour the limit and in the case when both have the same created timestamp, we can use the order in which they are added to decide. 
2. In the case when we have to choose both of them as a single unit, In that case, we can give users an option of how they wish to utilise a tie condition.

**Comment by renekrie** [comment]
@MighTguY, The idea in 1. would be to maybe expand the sort parameter to allow for a second (and third ...) criterion à la `sort=prio desc,timestamp desc`?

**Comment by MighTguY** [comment]
@renekrie yes that is one possible way of doing this, But the real motivation behind that is like in Solr/Lucene when  there is a tie, and no tiebreaker is mentioned then  the result set will be ordered according to Lucene 
DocID's if there's nothing to sort on

**Comment by renekrie** [comment]
Implemented and merged into master
