### ISSUE TITLE
deprecated warning for querqy.parser.WhiteSpaceQuerqyParserFactory

### ISSUE THREAD

**Issue by susheelks** [renekrie/querqy#57]
Hello Team,

Is there any way to remove deprecated warning. I am seeing this with Solr 6.6.2

SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [querqy.parser.WhiteSpaceQuerqyParserFactory]. Please consult documentation how to replace it accordingly.

Thanks,
Susheel

**Comment by renekrie** [comment]
Yes, you can replace it with querqy.rewrite.commonrules.WhiteSpaceQuerqyParserFactory in your solrconfig.xml. Also see the @deprecated annotation in querqy.parser.WhiteSpaceQuerqyParserFactory and the updated Querqy README).
