### ISSUE TITLE
Create Replace Rewriter

### ISSUE THREAD

**Issue by JohannesDaniel** [renekrie/querqy#64]
There should be a possibility to replace query terms. This will facilitate maintaining rules for different variants of terms, e. g. 
* i phone => iphone
* iphones => iphone

The replaced terms should not be marked as generated in order to allow applying subsequent common rules on it.

Furthermore, users should be allowed to define multiple tab-delimited inputs for an output, e. g. 
i phone	iphones	ihphone => iphone

**Comment by renekrie** [comment]
Implemented as of PR #65
